### ISSUE TITLE
能不能打包一下

### ISSUE THREAD

**Issue by inuxor** [uniorder/kedis#1]
**非node程序员**去配置npm，搞清楚各种报错的意思，对付大**墙**还是太费劲了

我从昨天折腾到现在才完成打包工作，这还是在前端工程师的提示下才做到的。让我自己永远想不到删除错误日志竟然会有效。。。。

**Comment by uniorder** [comment]
同样，我这边对付打墙也是很头疼，否则我也会将所有的版本都编译出来，不过放心我会尽力找到解决方法，你需要什么版本的？我先搞定你的版本。
