### ISSUE TITLE
显示乱码

### ISSUE THREAD

**Issue by trockxi** [uniorder/kedis#2]
在连接单机版时，会出现连接报错
![041702](https://user-images.githubusercontent.com/28647418/38853451-d8c45eb0-424f-11e8-84c5-49799728f6ae.png)
![041703](https://user-images.githubusercontent.com/28647418/38853459-e09031fa-424f-11e8-89a0-b375df19b555.png)
以及乱码
![041704](https://user-images.githubusercontent.com/28647418/38853510-0bb4cba2-4250-11e8-8e6e-2284d2eb5131.png)

而对cluster集群支持不是很好，只能通过一个master连到旗下的slave，而其他的master下看不到slave，有乱码
![0417](https://user-images.githubusercontent.com/28647418/38853582-53764fec-4250-11e8-8a8f-21e3029b50b6.png)

**Comment by uniorder** [comment]
目前测试的时候，发现在用Spring的RedisTemplate往里面写的时候会出现乱码，乱码原因是Spring在调用Jedis之前做了一个序列化操作，我目前在使用Spring的RedisTemplate的时候是自己又设置了一下序列化方式如下：
`@Configuration
public class RedisConfig {


    private final RedisTemplate redisTemplate;

    @Autowired
    public RedisConfig(RedisTemplate redisTemplate) {
        this.redisTemplate = redisTemplate;
    }

    @Bean
    public RedisTemplate redisTemplateInit() {
        RedisSerializer stringSerializer = new StringRedisSerializer();
        redisTemplate.setKeySerializer(stringSerializer);
        redisTemplate.setValueSerializer(stringSerializer);
        redisTemplate.setHashKeySerializer(stringSerializer);
        redisTemplate.setHashValueSerializer(stringSerializer);
        return redisTemplate;
    }
}
`
近期可能没有时间去解决这个问题，不过在我忙完手上的工作之后会去解决它。
另外，对于集群，我这边确实是没有针对集群进行开发，这个是我缺失的，我也会抽空对这个项目进行一次升级改造。
非常感谢你提出的问题。
