### ISSUE TITLE
一直在用，现在想把kedis上架深度商店，希望获得许可

### ISSUE THREAD

**Issue by YHYJ** [uniorder/kedis#4]
deepin linux新版商店提供赞赏功能，开发者:打包者:平台 = 6:2:2，您能不能把他上架，或者我来做打包者也行

**Comment by uniorder** [comment]
可以，但是我最近还发现了一些BUG，正在想办法解决（Hash分页有点问题）

**Comment by YHYJ** [comment]
您更新了的话，麻烦通知我一下吧，打包者要求在一个星期内跟着更新
yj1516268@outlook.com

**Comment by uniorder** [comment]
最近我在琢磨着重构一下，有一个bug是序列化的时候显示乱码，删不掉Key。

**Comment by uniorder** [comment]
由于GitHub实在太卡，整个项目迁移到Gitee上了，新项目地址为：https://gitee.com/hbase_admin/Kedis 这是全新的重构版本，修复了一些BUG，提升了性能。但是没有在Linux上测试，理论上是没有问题的。

**Comment by YHYJ** [comment]
OK，找时间我测试一下

**Comment by YHYJ** [comment]
您改了用户名邮件通知我一下呗，刚才审核没过，我一看是用户名改了，或者您github和gitee是同步的话用github的地址？

**Comment by YHYJ** [comment]
没事没事，我watch了gitee上的库，更新会自动通知我，但我不知道改名字什么的watch了会不会通知，您就把watch不会通知的修改啊什么的邮件通知我一下呗

**Comment by uniorder** [comment]
已经重构
